@URL=http://localhost:8080/culturas

###Criar uma cultura
POST {{URL}}
Content-Type: application/json

{
    "nome": "23",
    "tempoCultivoDias": 5,
    "epocaPlantio": "dasas"
}

###Deletar uma cultura
DELETE {{URL}}/10
Content-Type: application/json

###Editar uma cultura
PUT {{URL}}
Content-Type: application/json

{
    "id": 2,
    "nome": "clebinho",
    "tempoCultivoDias": 5,
    "epocaPlantio": "março"
}

###Receber uma cultura
GET {{URL}}/2
Content-Type: application/json