@URL=http://localhost:8080/propriedades

###Criar uma propriedade
POST {{URL}}
Content-Type: application/json

{
    "nome": "preguiça",
    "tamanhoHa": 5,
    "responsavel": "adolfo"
}

###Deletar uma propriedade
#DELETE {{URL}}/1
DELETE {{URL}}/1
Content-Type: application/json

###Editar uma propriedade
PUT {{URL}}
Content-Type: application/json

{
    "nome": "clebinho_pragas",
    "nomeCientifico": "angelica",
    "culturasAfetadas":[1],
    "descricao": "bla"
}

###Receber uma propriedade

GET {{URL}}
Content-Type: application/json